version : '2'
services:    
  mysqldbserver:
    build:
      context: . 
      dockerfile: mysqldb.dockerfile
    container_name: mysqldbserver 
    expose:
      - "3306"    
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: pismo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123     
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  app:
    build:
      context: . 
      dockerfile: springapp.dockerfile
    ports: 
      - "8080:8080"        
    environment:
      DATABASE_HOST: mysqldbserver
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: pismo_db
      DATABASE_PORT: 3306      
    depends_on:
      mysqldbserver: 
         condition: service_healthy